project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


quartodoc:
  parser: google
  # the name used to import the package you want to create reference docs for
  package: test_eyepy

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: VA conversions
      desc: Convert LogMAR to ETDRS.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - logmar_etdrs
